# Generated by Django 6.0.3 on 2026-04-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datasciencecourse', models.CharField(max_length=88)),
                ('AICourse', models.CharField(max_length=90)),
                ('Networkcourse', models.CharField(max_length=90)),
            ],
        ),
    ]
