# Generated by Django 6.0.3 on 2026-04-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScopeIndia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='othercourse',
            field=models.CharField(max_length=88, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='testcourse',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='AICourse',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Datasciencecourse',
            field=models.CharField(max_length=88, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Networkcourse',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
