# Generated by Django 6.0.3 on 2026-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScopeIndia', '0002_courses_othercourse_courses_testcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='othercourse',
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
    ]
