# Generated by Django 6.0.3 on 2026-04-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScopeIndia', '0003_alter_courses_othercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='AICourse',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Datasciencecourse',
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Networkcourse',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='testcourse',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
