# Generated by Django 6.0.3 on 2026-04-21 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScopeIndia', '0004_alter_courses_aicourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maincourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maincourse_name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Subcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcourse_name', models.CharField(max_length=90)),
                ('maincourse_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ScopeIndia.maincourse')),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
