# Generated by Django 6.0.3 on 2026-04-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScopeIndia', '0005_maincourse_subcourse_delete_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcourse',
            name='Course_duration',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='subcourse',
            name='course_timing',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='subcourse',
            name='course_title',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='subcourse',
            name='next_batch',
            field=models.CharField(null=True),
        ),
    ]
