# Generated by Django 6.0.3 on 2026-04-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScopeIndia', '0006_subcourse_course_duration_subcourse_course_timing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcourse',
            name='next_batch',
            field=models.DateField(null=True),
        ),
    ]
