# Generated by Django 6.0.3 on 2026-04-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScopeIndia', '0007_alter_subcourse_next_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='ScopeIndia.subcourse')),
            ],
        ),
    ]
