# Generated by Django 6.0.3 on 2026-05-09 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScopeIndia', '0008_coursecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=90)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=34)),
                ('eduqual', models.CharField(blank=True, max_length=90, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('guardname', models.CharField(blank=True, max_length=90, null=True)),
                ('guard_occu', models.CharField(blank=True, max_length=90, null=True)),
                ('guard_mob', models.CharField(blank=True, max_length=15, null=True)),
                ('course', models.CharField(max_length=90)),
                ('train_mode', models.CharField(blank=True, max_length=90, null=True)),
                ('location', models.CharField(blank=True, max_length=90, null=True)),
                ('timing', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=90, null=True)),
                ('state', models.CharField(blank=True, max_length=90, null=True)),
                ('city', models.CharField(blank=True, max_length=90, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='subcourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='ScopeIndia.subcourse'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
