# Generated by Django 6.0.3 on 2026-05-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScopeIndia', '0009_registration_alter_coursecontent_subcourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ScopeIndia.registration')),
            ],
        ),
    ]
