# Generated by Django 6.0.3 on 2026-05-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScopeIndia', '0010_studentlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogin',
            name='file',
            field=models.FileField(null=True, upload_to='Images/'),
        ),
    ]
